language: java
env:
  global:
  - secure: wjiSXh26aECXg2pZZc8LZw3Cs5B0x112humbFfF0HKIQrRI95RgOQIrYepTBxE6LE4Pyo9tnYn6WHncUpaWtvy7wtD3v6K6Lva0ueOnuHwATXAiFcAgKkBZz1avAJLy7eHuUwQU5yji3T924tgWH0f1x9bEqM0JtQD15zbLnbiFPdADmPB13eph656szgnAiXCu7gJ9YhQjQqhqwsQbxRzTTVK54x4NpF5Kz+tI/eRGcJJEVldYlv5mpm/8pQSlPpKgpwUY6bSdzPluCFMpPWRZAmLlfHJ0obYg9PCz/G4fC/Tqhchnj1rhNK7wAUEyMZ4trQ2NP5O22Nj9MHGllpf4hXi9EmAlHSY+CEtmheZH6ViWiM3F/DCOoLx4Lsk+GH7Yk/VsIdfhrK9tyhUn3THyI8PL46sfzx59ifhcyD4/uyv8jaETsGAI6FoOlNreVKIMZyG9p1HgZC8VpN7ll27KH2lhhSIu5qmBTSp89TihSBw6fHl+rMoOxSiO/M/nQSNXNpCVCkg6N1TQHB5Hm3C3gwbw6MhT1+jYPJE3dAq2TW5DyW/5r/P8eROp+JbA/vF4tRG5k+NmThXriP2m+9Uzmc1c899362SMMhSpaDXx1E4EYT/nvCbIDuyWThwwT13ueZIU754EKQicrG41A9mHtuc3sYr1GBqsqxRNIYUw=
  - secure: fQdgIcB2em6YEGMw4FjQkP3ICBRkjpYdNPkeDV1TC3cPjWl1YFmAnGxLGnPmb8L6jh5T8hjzwuXf5XSORgr0TuLcUZfEDRXwUI1WeS5CJ+eGqys2FQRINL+nPK4MirTv/TQR2YvCSgHWKSX9fbbTHdBbK3ai4YHLxyxaomAfVTD5TY7oiJcdgcdX39qxQBS4IKPRim/2h67mcOiY8dhGl/cd3sJb/+VKf+2KmZQFBVjyQTjzPL5/t3BlFUdzXVH0cd/vS7KB0nLCvPYKgXI4OIRhq0VbGjGtN9b8d4VaKqjF+O6DwAC1zGZzAwdLdR6+u0gbL8ydGf6GYuyV5rQ/+cR1kJ+UltGL3dqa+hNo8HpG90XYyEaAhj425qDhR7BvDsuhJOJt602CniQgNqe8vTMQ8xMAHtxKr/6BrFIu0+ETXD85ToslRmAR3JuAwxnasJ+WmiobAIm8rVLaJCZD3da4byaHF1Zgnw5watls7jmWn9Ro6U8XPmjR4ave8nGKl/2c0A32vGfaaI9fKNeFwFcW5B3MmrlmwMJ/1CAsFAXvWGDlufBIRbKxVDV7qgKwMSiPuUJKB8yiPWE776NJ1rfxIYMZ9OdNxuRYzutU5iDaSfDQFOw2NGtCjBdM9+dmNo5tLjEaq4LEDgoIiu7QnTcMfHdOHNI4RrH0K4HiJ5c=
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
install:
- mvn install
script:
- docker build -t my-walking-skeleton .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
- docker tag my-walking-skeleton aclaudel/my-walking-skeleton
- docker push aclaudel/my-walking-skeleton
deploy:
  provider: heroku
  api_key:
    secure: EmiMJHbTEpkQFiJDtzIAEK7n1AM9h84l/0h+hpDNnSMcwbGby2EhljkbqWwi84j0QVB9OcrA+Q3QZJhsjfRg193ugelgXowdQzkndhTdIs/dyNUYnTAfGk9YRkZPXV5pJcyZ2lvqtla/oUZ3NvkuULh7k9JmDVMUzGcUx6HFZJekIQJhllhwEW/RaPJM6ivv1C5el7gzmeheyLuEeqbl6TOz74ByGGO6RuGUZ7ANYUUXF6yuDS3cQ93saN8Xe1tDce8dvXuedGc87dpahzH48oQ82ETMKZBkQNSPzuHdvvwJ8LkYNw7C8hkPFyMXrVJPXZ/Xi+u20z0vM2kK6OhKA4mH0rywvjE4cEj+qnh5gtlCCdlpxDCsMgVcXCcHC+fLMtv7N04pySry1bNnla2jGqfHfLnTn5Ormb+u3Hrx0mCWavnEHpDd4dbxD5/r45FTgpj+fWnFhbYslw0FnuMsbNRbpPEXUej3Zk5teB4u0dkCK+4jg3sEOwk5Ot7Bafy8NIw7lRzJD0Bh6g5jZy8Y6qQzt2wvK/9Ut4RFCnUVloOnw/mPqLa+XtXvuogpZbcR2WF5yNsMJJ1Z/0vAuMEfcK5gpvYZ96WSzchIddUPQOboWghB5PQvSU+Jldf4qHEF5FIoM0b7eOGdqSHpkVfuK5TNITbTYsfqaAvL8aAbv2A=
  app: my-walking-skeleton
  on:
    repo: aclaudel/my-walking-skeleton
